// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SSC 2025 - Joy Bangla",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SSC 2025 - Joy Bangla",
            targets: ["AppModule"],
            bundleIdentifier: "msuappleacademy.SSC-2025---Joy-Bangla",
            teamIdentifier: "SD28Q5JP86",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .map),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "\"Joy Bangla\" requires camera access to detect surfaces and display augmented reality objects realistically in your environment.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)